name: "🐛 Bug report"
description: "File a bug/issue"
labels: ["bug"]
type: "bug"
body:
    - type: textarea
      id: current_behaviour
      attributes:
          label: Current Behaviour
          description: A concise description of what you are currently experiencing
      validations:
          required: true
    - type: textarea
      id: expected_behaviour
      attributes:
          label: Expected Behaviour
          description: A concise description of what is expected to happen
      validations:
          required: true
    - type: textarea
      id: steps_reproduce
      attributes:
          label: Steps To Reproduce
          description: Steps to reproduce the behavior.
          placeholder: |
              1. Go to...
              2. Click on...
              3. See error...
      validations:
          required: false
    - type: textarea
      attributes:
        label: Device Information [optional]
        description: |
          examples:
            - **OS**: Ubuntu 20.04
           - **Browser**: chrome
            - **version**: 22
        value: |
          - OS:
          - Browser:
          - version:
        render: markdown
      validations: 
        required: false
    - type: textarea
      id: anything_else
      attributes:
          label: Anything else?
          description: |
              Links? References? Anything that will give us more context about the issue you are encountering!

              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
          required: false
    - type: dropdown
      attributes:
        label: Are you willing to submit PR?
        options:
          - 'No'
          - 'Yes'
      validations: 
        required: true
